namespace: rws-${EnvironmentName}

namePrefix: rws-${EnvironmentName}-
commonLabels:
  releaseId: v${Octopus.Release.Id}
  releaseNumber: v${Octopus.Release.Number}
  deploymentId: ${Octopus.Deployment.Id}
  environment: ${EnvironmentName}
commonAnnotations:
  note: This is ${EnvironmentName}!
bases:
- ../../base
patches:
  - replica_count.yaml
  
configMapGenerator:
- name: configs
  behavior: merge
  env: octopus.configs