apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
spec:
  replicas: ${RWS:Ingest:Replicas}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: ${RWS:Api:Replicas}