apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ogazitt/node-env
        envFrom:
        - configMapRef:
            name: configs
        - secretRef:
            name: secrets