apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      containers:
      - name: ingest
        image: ogazitt/node-env
        envFrom:
        - configMapRef:
            name: configs
        - secretRef:
            name: secrets