apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: v0.1.0

images:
  - name: ogazitt/node-env
    newTag: latest
  - name: rws-ingest
    newTag: latest

configMapGenerator:
- name: configs
  env: configs

secretGenerator:
- name: secrets
  env: secrets
resources:
  - ingest.yaml
  # - offer.yaml
  # - publish.yaml
  - api.yaml
  - api-loadbalancer.yaml
